@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class SeplendidLogic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class SeplendidModel MODEL_COLOR
    Class Main #grey
    Class Commons LOGIC_COLOR_T2
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


UI -[#green]> SeplendidLogic
UI -right[#green]-> SeplendidModel
SeplendidLogic -[#blue]-> Storage
SeplendidLogic -down[#blue]-> SeplendidModel
Main -[#grey]-> UI
Main -[#grey]-> SeplendidLogic
Main -[#grey]-> Storage
Main -up[#grey]-> SeplendidModel
Main -down[hidden]-> Commons

Storage -up[STORAGE_COLOR].> SeplendidModel
Storage .right[STORAGE_COLOR].>File
User ..> UI
@enduml
