@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package SeplendidLogic as SeplendidLogicPackage {
Class "<<interface>>\nSeplendidLogic" as SeplendidLogic
Class SeplendidLogicManager
}

package SeplendidModel as SeplendidModelPackage {
Class "<<interface>>\nSeplendidModel" as SeplendidModel
Class SeplendidModelManager
}

package Storage as StoragePackage {
Class "<<interface>>\nStorage" as Storage
Class StorageManager
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> SeplendidLogic

SeplendidLogicManager .up.|> SeplendidLogic
SeplendidModelManager .up.|> SeplendidModel
StorageManager .up.|> Storage

SeplendidLogicManager --> SeplendidModel
SeplendidLogicManager --> Storage
@enduml
