@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package SeplendidLogic as SeplendidLogicPackage {

Class SeplendidParser
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command


Class "<<interface>>\nSeplendidLogic" as SeplendidLogic
Class SeplendidLogicManager
}

package SeplendidModel {
Class HiddenModel #FFFFFF
}

package Storage {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> SeplendidLogic

SeplendidLogicManager .right.|> SeplendidLogic
SeplendidLogicManager -right->"1" SeplendidParser
SeplendidParser ..> XYZCommand : creates >

XYZCommand -up-|> Command
SeplendidLogicManager .left.> Command : executes >

SeplendidLogicManager --> SeplendidModel
SeplendidLogicManager --> Storage
Storage --[hidden] SeplendidModel
Command .[hidden]up.> Storage
Command .right.> SeplendidModel
note right of XYZCommand: XYZCommand = NoteAddCommand, \nLocalCourseAddCommand, etc

SeplendidLogic ..> CommandResult
SeplendidLogicManager .down.> CommandResult
Command .up.> CommandResult : produces >
@enduml
