@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Package SeplendidModel as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyLocalCourseCatalogue" as ReadOnlyLocalCourseCatalogue
Class "<<interface>>\nReadOnlyPartnerCourseCatalogue" as ReadOnlyPartnerCourseCatalogue
Class "<<interface>>\nReadOnlyUniversityCatalogue" as ReadOnlyUniversityCatalogue
Class "<<interface>>\nReadOnlyMappingCatalogue" as ReadOnlyMappingCatalogue
Class "<<interface>>\nSeplendidModel" as SeplendidModel
Class LocalCourseCatalogue
Class PartnerCourseCatalogue
Class UniversityCatalogue
Class MappingCatalogue

Class HiddenOutside #FFFFFF
HiddenOutside ..> SeplendidModel

Class SeplendidModelManager

Class UniqueLocalCourseList
Class UniquePartnerCourseList
Class UniqueMappingList
Class UniqueUniversityList

Class LocalCourse
Class LocalCode
Class LocalName
Class LocalUnit
Class LocalDescription

Class PartnerCourse
Class PartnerCode
Class PartnerName
Class PartnerUnit
Class PartnerDescription

Class University
Class UniversityName

Class Mapping
Class MappingMiscInformation

LocalCourseCatalogue .up.|> ReadOnlyLocalCourseCatalogue
PartnerCourseCatalogue .up.|> ReadOnlyPartnerCourseCatalogue
UniversityCatalogue .up.|> ReadOnlyUniversityCatalogue
MappingCatalogue .up.|> ReadOnlyMappingCatalogue

SeplendidModelManager .up.|> SeplendidModel
SeplendidModel .left.> ReadOnlyLocalCourseCatalogue
SeplendidModel .left.> ReadOnlyPartnerCourseCatalogue
SeplendidModel .left.> ReadOnlyMappingCatalogue
SeplendidModel .right.> ReadOnlyUniversityCatalogue

SeplendidModelManager -left-> "1" LocalCourseCatalogue
SeplendidModelManager -left-> "1" PartnerCourseCatalogue
SeplendidModelManager -left-> "1" UniversityCatalogue
SeplendidModelManager -right-> "1" MappingCatalogue

LocalCourseCatalogue *--> "1" UniqueLocalCourseList
UniqueLocalCourseList --> "~* all" LocalCourse
PartnerCourseCatalogue *--> "1" UniquePartnerCourseList
UniquePartnerCourseList --> "~* all" PartnerCourse
UniversityCatalogue *--> "1" UniqueUniversityList
UniqueUniversityList --> "~* all" University
MappingCatalogue *--> "1" UniqueMappingList
UniqueMappingList --> "~* all" Mapping

LocalCourse *--> "1" LocalCode
LocalCourse *--> "1" LocalName
LocalCourse *--> "1" LocalUnit
LocalCourse *--> "1" LocalDescription

PartnerCourse *--> "1" PartnerCode
PartnerCourse *--> "1" PartnerName
PartnerCourse *--> "1" PartnerUnit
PartnerCourse *--> "1" PartnerDescription

University *--> "1" UniversityName

Mapping *--> "1" MappingMiscInformation
Mapping ---> "1" LocalCode
Mapping ---> "1" PartnerCode
Mapping ---> "1" UniversityName

SeplendidModelManager -[#blue]-> "~* filtered/\nsorted" LocalCourse
SeplendidModelManager -[#blue]-> "~* filtered/\nsorted" PartnerCourse
SeplendidModelManager -[#blue]-> "~* filtered/\nsorted" University
SeplendidModelManager -[#blue]-> "~* filtered/\nsorted" Mapping
@enduml
