@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters command;
:Command string is passed into\nSeplendidParser#parseCommand;
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
if () then ([command has commandWord,\nactionWord and arguments])
    -Pass userInput into\nSeplendidParser\n #parseCommandActionArg
    -commandWord, actionWord,\narguments extracted
    -Pass userinput, actionWord and arguments\ninto respective getCommandWithArg\nmethods, based on commandWord
elseif () then ([command has commandWord,\nand actionWord only])
    -Pass userInput into\nSeplendidParser\n #parseCommandAction
    -commandWord, actionWord\nextracted
    -Pass userinput, actionWord\ninto respective getCommandWithoutArg\nmethods, based on commandWord
else ([command has commandWord only])
    -Pass userInput into\nSeplendidParser\n #parseCommandOnly
    -commandWord extracted
    -Based on commandWord,\neither a HelpCommand or\nExitCommand is returned

endif
-Command is returned to Logic and Command#execute is called
stop
@enduml
