@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "Storage" #F4F6F6{
Class "<<interface>>\nLocalCourseCatalogueStorage" as LocalCourseCatalogueStorage
Class "<<interface>>\nPartnerCourseCatalogueStorage" as PartnerCourseCatalogueStorage
Class "<<interface>>\nUniversityCatalogueStorage" as UniversityCatalogueStorage
Class "<<interface>>\nMappingCatalogueStorage" as MappingCatalogueStorage
Class "<<interface>>\nNoteCatalogueStorage" as NoteCatalogueStorage

Class JsonLocalCourseCatalogueStorage
Class JsonSerializableLocalCourseCatalogue
Class JsonPartnerCourseCatalogueStorage
Class JsonSerializablePartnerCourseCatalogue
Class JsonUniversityCatalogueStorage
Class JsonSerializableUniversityCatalogue
Class JsonMappingCatalogueStorage
Class JsonSerializableMappingCatalogue
Class JsonNoteCatalogueStorage
Class JsonSerializableNoteCatalogue

Class JsonAdaptedTag
Class JsonAdaptedLocalCourse
Class JsonAdaptedPartnerCourse
Class JsonAdaptedMapping
Class JsonAdaptedUniversity
Class JsonAdaptedNote

StorageManager .up.|> Storage
StorageManager -down-> "1" UserPrefsStorage
StorageManager -up-> "1" LocalCourseCatalogueStorage
StorageManager -up-> "1" PartnerCourseCatalogueStorage
StorageManager -down-> "1" MappingCatalogueStorage
StorageManager -up-> "1" UniversityCatalogueStorage
StorageManager -up-> "1" NoteCatalogueStorage

Storage -left-|> LocalCourseCatalogueStorage
Storage -left-|> PartnerCourseCatalogueStorage
Storage -left-|> UniversityCatalogueStorage
Storage -down-|> MappingCatalogueStorage
Storage -right-|> NoteCatalogueStorage
Storage -right-|> UserPrefsStorage


JsonUserPrefsStorage .up.|> UserPrefsStorage

JsonLocalCourseCatalogueStorage .up.|> LocalCourseCatalogueStorage
JsonLocalCourseCatalogueStorage ..> JsonSerializableLocalCourseCatalogue
JsonSerializableLocalCourseCatalogue --> "*" JsonAdaptedLocalCourse

JsonPartnerCourseCatalogueStorage .up.|> PartnerCourseCatalogueStorage
JsonPartnerCourseCatalogueStorage ..> JsonSerializablePartnerCourseCatalogue
JsonSerializablePartnerCourseCatalogue --> "*" JsonAdaptedPartnerCourse

JsonUniversityCatalogueStorage .up.|> UniversityCatalogueStorage
JsonUniversityCatalogueStorage ..> JsonSerializableUniversityCatalogue
JsonSerializableUniversityCatalogue --> "*" JsonAdaptedUniversity

JsonMappingCatalogueStorage .up.|> MappingCatalogueStorage
JsonMappingCatalogueStorage ..> JsonSerializableMappingCatalogue
JsonSerializableMappingCatalogue --> "*" JsonAdaptedMapping

JsonNoteCatalogueStorage .up.|> NoteCatalogueStorage
JsonNoteCatalogueStorage ..> JsonSerializableNoteCatalogue
JsonSerializableNoteCatalogue --> "*" JsonAdaptedNote
JsonAdaptedNote --> "*" JsonAdaptedTag
@enduml
