@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class HelpWindow
Class MainWindow
Class CommandBox
Class ResultDisplay
Class ItemListPanel
Class LocalCourseItem
Class PartnerCourseItem
Class MappingItem
Class UniversityItem
Class NoteItem
Class ItemDetailPanel
Class LocalCourseDetail
Class PartnerCourseDetail
Class MappingDetail
Class UniversityDetail
Class NoteDetail
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow

MainWindow *-down-> "1" ItemListPanel
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow -down-|> UiPart
MainWindow --> "0..1" HelpWindow
MainWindow *-down-> "1" ItemDetailPanel


ItemListPanel -down-> "*" LocalCourseItem
ItemListPanel -down-> "*" PartnerCourseItem
ItemListPanel -down-> "*" MappingItem
ItemListPanel -down-> "*" UniversityItem
ItemListPanel -down-> "*" NoteItem

ItemDetailPanel -down-> "*" LocalCourseDetail
ItemDetailPanel -down-> "*" PartnerCourseDetail
ItemDetailPanel -down-> "*" MappingDetail
ItemDetailPanel -down-> "*" UniversityDetail
ItemDetailPanel -down-> "*" NoteDetail

LocalCourseItem ..> Model
PartnerCourseItem ..> Model
MappingItem ..> Model
UniversityItem ..> Model
NoteItem ..> Model
LocalCourseDetail ..> Model
PartnerCourseDetail ..> Model
MappingDetail ..> Model
UniversityDetail ..> Model
NoteDetail ..> Model

UiManager -right-> Logic
MainWindow -right-> Logic

ItemListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay

MainWindow -[hidden]-|> UiPart
HelpWindow --|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
ItemListPanel --|> UiPart
ItemDetailPanel --|> UiPart
LocalCourseItem --|> UiPart
PartnerCourseItem --|> UiPart
MappingItem --|> UiPart
UniversityItem --|> UiPart
NoteItem --|> UiPart
LocalCourseDetail --|> UiPart
PartnerCourseDetail --|> UiPart
MappingDetail --|> UiPart
UniversityDetail --|> UiPart
NoteDetail --|> UiPart

@enduml
